package template

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
	"golang_telegram_bot/internal/models/currency"
	"time"
)

func BaseCurrenciesTemplate() map[string]*currency.Currency {
	return map[string]*currency.Currency{
		"GBP": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Фунт стерлингов Соединенного королевства",
			Code:      "GBP",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"AMD": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "֏",
			Name:      "Армянских драмов",
			Code:      "AMD",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"BYN": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Белорусский рубль",
			Code:      "BYN",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"HKD": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Гонконгских долларов",
			Code:      "HKD",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"USD": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Доллар США",
			Code:      "USD",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"EUR": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Евро",
			Code:      "EUR",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"INR": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₹",
			Name:      "Индийских рупий",
			Code:      "INR",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"KZT": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₸",
			Name:      "Казахстанских тенге",
			Code:      "KZT",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"KGS": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "KGS",
			Name:      "Киргизских сомов",
			Code:      "KGS",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"CNY": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Китайских юаней",
			Code:      "CNY",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"TJS": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Таджикских сомони",
			Code:      "TJS",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"TRY": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Турецких лир",
			Code:      "TRY",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"UZS": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "UZS",
			Name:      "Узбекских сумов",
			Code:      "UZS",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"UAH": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Украинских гривен",
			Code:      "UAH",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
		"CHF": &currency.Currency{
			ID:        primitive.NewObjectID(),
			Amount:    0,
			Icon:      "₽",
			Name:      "Швейцарский франк",
			Code:      "CHF",
			CreatedAt: time.Now(),
			UpdatedAt: time.Now(),
		},
	}
}
